/**
 * Stable, machine-readable error codes returned in API error responses.
 * Frontend clients should branch on `errorCode`, never on the human `message`.
 */
export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Rooms
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_NOT_AVAILABLE = 'ROOM_NOT_AVAILABLE',
  ROOM_INACTIVE = 'ROOM_INACTIVE',
  ROOM_UNDER_MAINTENANCE = 'ROOM_UNDER_MAINTENANCE',
  ROOM_CAPACITY_EXCEEDED = 'ROOM_CAPACITY_EXCEEDED',
  ROOM_NUMBER_EXISTS = 'ROOM_NUMBER_EXISTS',
  ROOM_IMAGE_NOT_FOUND = 'ROOM_IMAGE_NOT_FOUND',

  // Room types / facilities
  ROOM_TYPE_NOT_FOUND = 'ROOM_TYPE_NOT_FOUND',
  ROOM_TYPE_IN_USE = 'ROOM_TYPE_IN_USE',
  FACILITY_NOT_FOUND = 'FACILITY_NOT_FOUND',

  // Bookings
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_ALREADY_PROCESSED = 'BOOKING_ALREADY_PROCESSED',
  BOOKING_NOT_CANCELLABLE = 'BOOKING_NOT_CANCELLABLE',
  INVALID_BOOKING_DATES = 'INVALID_BOOKING_DATES',

  // Offers
  OFFER_NOT_FOUND = 'OFFER_NOT_FOUND',

  // Uploads
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
}
